### ISSUE TITLE
How to get the values?

### ISSUE THREAD

**Issue by creatiolabsmx** [EurekaCommunity/CreditCardRow#13]
I need the values of creditCardNumber, expiration and cvv

**Comment by mats-claassen** [comment]
As with all the Eureka rows, `row.value` gives you the value of the row. In this case the value is of type `CreditCardInfo` which is a struct that contains the values you need.

**Comment by nootfly** [comment]
self.form.values() does not return credit card fields' values.

**Comment by mats-claassen** [comment]
Did you set a tag for the row?

**Comment by nootfly** [comment]
Thanks. After I set a tag, it works.
