### ISSUE TITLE
Dependency issue to Eureka 3.1.0

### ISSUE THREAD

**Issue by felipeplets** [EurekaCommunity/CreditCardRow#4]
I've tried to install CreditCardRow in my project that dependes on Eureka 3.1.0 but it fails since CreditCardRow requires 3.0. 

```
pod install
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `Eureka (= 3.1.0)` required by `Podfile`
- `Eureka (= 3.1.0)` required by `Podfile.lock`
- `Eureka (= 3.0)` required by `CreditCardRow (2.1.0)`
```

**Comment by mats-claassen** [comment]
Closing this as we have moved to Eureka 4, but I think you could have fixed that using `pod update`

**Comment by felipeplets** [comment]
@mats-claassen it is still an issue, just moved to the next version now the requirement is fixed on version 4.0.0 and I can update my Eureka to 4.0.1 because of CreditCardRow. 

The correct way would be to add one of the following options on the CreditCardRow.podspec: 
`s.dependency 'Eureka', '~> 4'`
or
`s.dependency 'Eureka', '~> 4.0' # if you want to be more conservative.`

**Comment by mats-claassen** [comment]
Yes I would prefer `4.0`. Could you update that pull request?

**Comment by felipeplets** [comment]
@mats-claassen updated

**Comment by mats-claassen** [comment]
Merged
